"""add_phone_number

Revision ID: 1a36c210caec
Revises: a9b06dc3ac08
Create Date: 2023-03-26 16:18:45.310789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a36c210caec'
down_revision = 'a9b06dc3ac08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
