"""add_number_phone_only

Revision ID: 78b539b3da00
Revises: 88b21c506d5f
Create Date: 2023-03-26 16:23:03.436357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b539b3da00'
down_revision = '88b21c506d5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
