"""toto

Revision ID: 88b21c506d5f
Revises: b88594025f90
Create Date: 2023-03-26 16:22:21.055547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b21c506d5f'
down_revision = 'b88594025f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_column')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
